### ISSUE TITLE
Add alternative palette formats

### ISSUE THREAD

**Issue by ThatOneCalculator** [rose-pine/rose-pine-site#5]
As I use the pallete site to edit CSS a lot, in the old version, double-clicking and copying would only copy `232136` for example, which was very convenient, but now it copies `#232136`, which is far less convenient.

**Comment by mvllow** [comment]
This is tough because I feel like copying the entire hex with `#` is more common and matches the other two options when copying rgb as `rgb(...)` and hsl as `hsl(...)`. There are definitely times where the `#` gets in the way, though. Maybe there could be display option for formatted or unformatted values in the colour table

On a side note, our palette tool was just updated to include css

**Comment by mvllow** [comment]
I like what radix-ui does on their site: https://www.radix-ui.com/docs/colors/palette-composition/the-scales, thoughts? This does add an extra click to actually copy a value but would allow us to copy in several formats, for example:

- `--rose: #ebbcba` (css)
- `$rose: #ebbcba` (scss)
- `ebbcba` (unformatted)

**Comment by ThatOneCalculator** [comment]
> I like what radix-ui does on their site: https://www.radix-ui.com/docs/colors/palette-composition/the-scales, thoughts? This does add an extra click to actually copy a value but would allow us to copy in several formats, for example:
> 
>     * `--rose: #ebbcba` (css)
> 
>     * `$rose: #ebbcba` (scss)
> 
>     * `ebbcba` (unformatted)
> 
> 
> edit: an additional thought would be to have a format dropdown on each card under ingredients vs a dropdown per color

This *could* work if it's easily keyboard navigable. Like a `tab` `tab`' `space` or a `tab` `tab` `down arrow` `space`.
